blank_issues_enabled: false
contact_links:
  - name: GitHub Community Support
    url: https://github.com/yourusername/RuleEngine/discussions
    about: Please ask and answer questions here.
  - name: Stack Overflow
    url: https://stackoverflow.com/questions/tagged/ruleengine
    about: Please ask questions about using RuleEngine on Stack Overflow with the tag 'ruleengine'.

