# This file sets the default permissions for GitHub Actions workflows
# It ensures that workflows have the minimum required permissions

# Default permissions for all workflows
permissions:
  contents: read
  issues: write
  pull-requests: write
  packages: write
  security-events: write
  actions: read
  checks: write
  statuses: write
  deployments: write
  pages: write
  discussions: write
  metadata: read